# Generated by Django 5.2.7 on 2025-11-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='height_feet',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='height_inches',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='weight_pounds',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='weight_stone',
        ),
    ]
