# Generated by Django 5.2.7 on 2025-12-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_height_feet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='height_feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='height_inches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight_pounds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight_stone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
