# Generated by Django 5.2.7 on 2025-12-18 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='height',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='weightentry',
            options={},
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='pounds',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='stones',
        ),
        migrations.AddField(
            model_name='weightentry',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weightentry',
            name='weight_pounds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='weight_stones',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Height',
        ),
    ]
