# Generated by Django 5.2.7 on 2025-12-18 11:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_height_user_alter_weightentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightentry',
            name='date_recorded',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='weight_pounds',
        ),
        migrations.RemoveField(
            model_name='weightentry',
            name='weight_stones',
        ),
        migrations.AddField(
            model_name='weightentry',
            name='pounds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weightentry',
            name='stones',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_stones', models.PositiveIntegerField()),
                ('target_pounds', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feet', models.PositiveIntegerField()),
                ('inches', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='height', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
