# Generated by Django 5.2.7 on 2025-12-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_weightentry_date_recorded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='stones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
