# Generated by Django 5.2.7 on 2025-12-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_weightentry_stones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Height',
        ),
    ]
